# Generated by Django 4.2.1 on 2023-05-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pblisher',
            new_name='publisher',
        ),
    ]
