# Generated by Django 4.1.7 on 2023-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profie_pic',
            field=models.ImageField(default='', upload_to='profile_pic/'),
        ),
    ]
