# Generated by Django 4.1.7 on 2023-03-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_profie_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profie_pic',
            new_name='profile_pic',
        ),
    ]
